"""add study profile and daily plan system

Revision ID: 4b0e145acbf6
Revises: b4aeb2e06f22
Create Date: 2026-03-09 12:11:09.257896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b0e145acbf6'
down_revision: Union[str, Sequence[str], None] = 'b4aeb2e06f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vocab_target', sa.Integer(), nullable=True),
    sa.Column('kanji_target', sa.Integer(), nullable=True),
    sa.Column('grammar_target', sa.Integer(), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('listening_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jlpt_level', sa.Enum('N5', 'N4', 'N3', 'N2', 'N1', name='jlptlevel'), nullable=False),
    sa.Column('target_exam_date', sa.Date(), nullable=True),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.Column('vocab_known', sa.Integer(), nullable=True),
    sa.Column('kanji_known', sa.Integer(), nullable=True),
    sa.Column('grammar_known', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('plan_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vocab_done', sa.Integer(), nullable=True),
    sa.Column('kanji_done', sa.Integer(), nullable=True),
    sa.Column('grammar_done', sa.Integer(), nullable=True),
    sa.Column('reading_minutes_done', sa.Integer(), nullable=True),
    sa.Column('listening_minutes_done', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.add_column('performance_logs', sa.Column('activity_source', sa.String(), nullable=True))
    op.add_column('performance_logs', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('performance_logs', 'reflection_note')
    op.drop_column('performance_logs', 'confidence_rating')
    op.drop_column('study_sessions', 'skill_type')
    # ### end Alembic commands ###


def downgrade() -> None:
   pass
