"""initial schema

Revision ID: d1aaadeb99e5
Revises: 
Create Date: 2026-03-01 15:38:26.419429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aaadeb99e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.Enum('pattern', 'weakness', 'progress', 'warning', 'recommendation', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_updated_at'), 'insights', ['updated_at'], unique=False)
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_index(op.f('ix_insights_valid_until'), 'insights', ['valid_until'], unique=False)
    op.create_table('next_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_actions_created_at'), 'next_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_next_actions_user_id'), 'next_actions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.Enum('vocab', 'grammar', 'reading', 'listening', name='skilltype'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('time_of_day_bucket', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_created_at'), 'study_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('performance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('perceived_performance', sa.Float(), nullable=False),
    sa.Column('primary_struggle', sa.Enum('particle', 'vocabulary', 'grammar_structure', 'reading_inference', 'listening_detail', 'kanji', 'time_pressure', name='mistaketype'), nullable=False),
    sa.Column('focus_level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('confidence_rating', sa.Integer(), nullable=True),
    sa.Column('reflection_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='check_difficulty_range'),
    sa.CheckConstraint('focus_level >= 1 AND focus_level <= 5', name='check_focus_range'),
    sa.CheckConstraint('perceived_performance >= 0 AND perceived_performance <= 1', name='check_performance_range'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_logs_id'), 'performance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_performance_logs_primary_struggle'), 'performance_logs', ['primary_struggle'], unique=False)
    op.create_index(op.f('ix_performance_logs_session_id'), 'performance_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_logs_session_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_primary_struggle'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_id'), table_name='performance_logs')
    op.drop_table('performance_logs')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_created_at'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_next_actions_user_id'), table_name='next_actions')
    op.drop_index(op.f('ix_next_actions_created_at'), table_name='next_actions')
    op.drop_table('next_actions')
    op.drop_index(op.f('ix_insights_valid_until'), table_name='insights')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_updated_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
